version: '3.12.12'

services:
  app:
    build: .
    restart: always
    expose:
      - 8080 #mettere expose al posto di ports e 8080 sotto
    networks:
      - global-network
    volumes:
      - /logs:/logs  # Monta la directory dei log sul tuo host

networks:
  global-network:
    external: true
